package entity;
// Generated Apr 1, 2019 7:59:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CanHo generated by hbm2java
 */
public class CanHo  implements java.io.Serializable {


     private String canHoId;
     private String maSoCanHo;
     private String khachHangId;
     private Short tang;
     private Set<ThongTinKhachHang> thongTinKhachHangs = new HashSet<ThongTinKhachHang>(0);
     private Set<HoaDonInternet> hoaDonInternets = new HashSet<HoaDonInternet>(0);
     private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);
     private Set<HoaDonDichVu> hoaDonDichVus = new HashSet<HoaDonDichVu>(0);
     private Set<HoaDonSinhHoat> hoaDonSinhHoats = new HashSet<HoaDonSinhHoat>(0);

    public CanHo() {
    }

	
    public CanHo(String canHoId) {
        this.canHoId = canHoId;
    }
    public CanHo(String canHoId, String maSoCanHo, String khachHangId, Short tang, Set<ThongTinKhachHang> thongTinKhachHangs, Set<HoaDonInternet> hoaDonInternets, Set<HoaDon> hoaDons, Set<HoaDonDichVu> hoaDonDichVus, Set<HoaDonSinhHoat> hoaDonSinhHoats) {
       this.canHoId = canHoId;
       this.maSoCanHo = maSoCanHo;
       this.khachHangId = khachHangId;
       this.tang = tang;
       this.thongTinKhachHangs = thongTinKhachHangs;
       this.hoaDonInternets = hoaDonInternets;
       this.hoaDons = hoaDons;
       this.hoaDonDichVus = hoaDonDichVus;
       this.hoaDonSinhHoats = hoaDonSinhHoats;
    }
   
    public String getCanHoId() {
        return this.canHoId;
    }
    
    public void setCanHoId(String canHoId) {
        this.canHoId = canHoId;
    }
    public String getMaSoCanHo() {
        return this.maSoCanHo;
    }
    
    public void setMaSoCanHo(String maSoCanHo) {
        this.maSoCanHo = maSoCanHo;
    }
    public String getKhachHangId() {
        return this.khachHangId;
    }
    
    public void setKhachHangId(String khachHangId) {
        this.khachHangId = khachHangId;
    }
    public Short getTang() {
        return this.tang;
    }
    
    public void setTang(Short tang) {
        this.tang = tang;
    }
    public Set<ThongTinKhachHang> getThongTinKhachHangs() {
        return this.thongTinKhachHangs;
    }
    
    public void setThongTinKhachHangs(Set<ThongTinKhachHang> thongTinKhachHangs) {
        this.thongTinKhachHangs = thongTinKhachHangs;
    }
    public Set<HoaDonInternet> getHoaDonInternets() {
        return this.hoaDonInternets;
    }
    
    public void setHoaDonInternets(Set<HoaDonInternet> hoaDonInternets) {
        this.hoaDonInternets = hoaDonInternets;
    }
    public Set<HoaDon> getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }
    public Set<HoaDonDichVu> getHoaDonDichVus() {
        return this.hoaDonDichVus;
    }
    
    public void setHoaDonDichVus(Set<HoaDonDichVu> hoaDonDichVus) {
        this.hoaDonDichVus = hoaDonDichVus;
    }
    public Set<HoaDonSinhHoat> getHoaDonSinhHoats() {
        return this.hoaDonSinhHoats;
    }
    
    public void setHoaDonSinhHoats(Set<HoaDonSinhHoat> hoaDonSinhHoats) {
        this.hoaDonSinhHoats = hoaDonSinhHoats;
    }




}


