package entity;
// Generated Apr 1, 2019 7:59:34 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * HoaDonInternet generated by hbm2java
 */
public class HoaDonInternet  implements java.io.Serializable {


     private Serializable hoaDonInternetId;
     private CanHo canHo;
     private HoaDon hoaDon;
     private Serializable ngayThang;
     private Double tien;

    public HoaDonInternet() {
    }

	
    public HoaDonInternet(Serializable hoaDonInternetId) {
        this.hoaDonInternetId = hoaDonInternetId;
    }
    public HoaDonInternet(Serializable hoaDonInternetId, CanHo canHo, HoaDon hoaDon, Serializable ngayThang, Double tien) {
       this.hoaDonInternetId = hoaDonInternetId;
       this.canHo = canHo;
       this.hoaDon = hoaDon;
       this.ngayThang = ngayThang;
       this.tien = tien;
    }
   
    public Serializable getHoaDonInternetId() {
        return this.hoaDonInternetId;
    }
    
    public void setHoaDonInternetId(Serializable hoaDonInternetId) {
        this.hoaDonInternetId = hoaDonInternetId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public HoaDon getHoaDon() {
        return this.hoaDon;
    }
    
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }
    public Serializable getNgayThang() {
        return this.ngayThang;
    }
    
    public void setNgayThang(Serializable ngayThang) {
        this.ngayThang = ngayThang;
    }
    public Double getTien() {
        return this.tien;
    }
    
    public void setTien(Double tien) {
        this.tien = tien;
    }




}


