package entity;
// Generated Apr 1, 2019 7:59:34 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * HoaDon generated by hbm2java
 */
public class HoaDon  implements java.io.Serializable {


     private String hoaDonId;
     private CanHo canHo;
     private Users users;
     private String ngayLap;
     private Double tongTien;
     private String ten;
     private Set<HoaDonDichVu> hoaDonDichVus = new HashSet<HoaDonDichVu>(0);
     private Set<HoaDonInternet> hoaDonInternets = new HashSet<HoaDonInternet>(0);
     private Set<HoaDonSinhHoat> hoaDonSinhHoats = new HashSet<HoaDonSinhHoat>(0);

    public HoaDon() {
    }

	
    public HoaDon(String hoaDonId) {
        this.hoaDonId = hoaDonId;
    }
    public HoaDon(String hoaDonId, CanHo canHo, Users users, String ngayLap, Double tongTien, String ten, Set<HoaDonDichVu> hoaDonDichVus, Set<HoaDonInternet> hoaDonInternets, Set<HoaDonSinhHoat> hoaDonSinhHoats) {
       this.hoaDonId = hoaDonId;
       this.canHo = canHo;
       this.users = users;
       this.ngayLap = ngayLap;
       this.tongTien = tongTien;
       this.ten = ten;
       this.hoaDonDichVus = hoaDonDichVus;
       this.hoaDonInternets = hoaDonInternets;
       this.hoaDonSinhHoats = hoaDonSinhHoats;
    }
   
    public String getHoaDonId() {
        return this.hoaDonId;
    }
    
    public void setHoaDonId(String hoaDonId) {
        this.hoaDonId = hoaDonId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getNgayLap() {
        return this.ngayLap;
    }
    
    public void setNgayLap(String ngayLap) {
        this.ngayLap = ngayLap;
    }
    public Double getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Double tongTien) {
        this.tongTien = tongTien;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set<HoaDonDichVu> getHoaDonDichVus() {
        return this.hoaDonDichVus;
    }
    
    public void setHoaDonDichVus(Set<HoaDonDichVu> hoaDonDichVus) {
        this.hoaDonDichVus = hoaDonDichVus;
    }
    public Set<HoaDonInternet> getHoaDonInternets() {
        return this.hoaDonInternets;
    }
    
    public void setHoaDonInternets(Set<HoaDonInternet> hoaDonInternets) {
        this.hoaDonInternets = hoaDonInternets;
    }
    public Set<HoaDonSinhHoat> getHoaDonSinhHoats() {
        return this.hoaDonSinhHoats;
    }
    
    public void setHoaDonSinhHoats(Set<HoaDonSinhHoat> hoaDonSinhHoats) {
        this.hoaDonSinhHoats = hoaDonSinhHoats;
    }




}


