package entity;
// Generated Apr 1, 2019 7:59:34 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * HoaDonSinhHoat generated by hbm2java
 */
public class HoaDonSinhHoat  implements java.io.Serializable {


     private String hoaDonSinhHoatId;
     private CanHo canHo;
     private HoaDon hoaDon;
     private Date ngayThang;
     private Integer chiSoDienBanDau;
     private Integer chiSoDienCuoi;
     private Double tienDien;
     private Integer chiSoNuocBanDau;
     private Integer chiSoNuocCuoi;
     private Double tienNuoc;

    public HoaDonSinhHoat() {
    }

	
    public HoaDonSinhHoat(String hoaDonSinhHoatId) {
        this.hoaDonSinhHoatId = hoaDonSinhHoatId;
    }
    public HoaDonSinhHoat(String hoaDonSinhHoatId, CanHo canHo, HoaDon hoaDon, Date ngayThang, Integer chiSoDienBanDau, Integer chiSoDienCuoi, Double tienDien, Integer chiSoNuocBanDau, Integer chiSoNuocCuoi, Double tienNuoc) {
       this.hoaDonSinhHoatId = hoaDonSinhHoatId;
       this.canHo = canHo;
       this.hoaDon = hoaDon;
       this.ngayThang = ngayThang;
       this.chiSoDienBanDau = chiSoDienBanDau;
       this.chiSoDienCuoi = chiSoDienCuoi;
       this.tienDien = tienDien;
       this.chiSoNuocBanDau = chiSoNuocBanDau;
       this.chiSoNuocCuoi = chiSoNuocCuoi;
       this.tienNuoc = tienNuoc;
    }
   
    public String getHoaDonSinhHoatId() {
        return this.hoaDonSinhHoatId;
    }
    
    public void setHoaDonSinhHoatId(String hoaDonSinhHoatId) {
        this.hoaDonSinhHoatId = hoaDonSinhHoatId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public HoaDon getHoaDon() {
        return this.hoaDon;
    }
    
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }
    public Date getNgayThang() {
        return this.ngayThang;
    }
    
    public void setNgayThang(Date ngayThang) {
        this.ngayThang = ngayThang;
    }
    public Integer getChiSoDienBanDau() {
        return this.chiSoDienBanDau;
    }
    
    public void setChiSoDienBanDau(Integer chiSoDienBanDau) {
        this.chiSoDienBanDau = chiSoDienBanDau;
    }
    public Integer getChiSoDienCuoi() {
        return this.chiSoDienCuoi;
    }
    
    public void setChiSoDienCuoi(Integer chiSoDienCuoi) {
        this.chiSoDienCuoi = chiSoDienCuoi;
    }
    public Double getTienDien() {
        return this.tienDien;
    }
    
    public void setTienDien(Double tienDien) {
        this.tienDien = tienDien;
    }
    public Integer getChiSoNuocBanDau() {
        return this.chiSoNuocBanDau;
    }
    
    public void setChiSoNuocBanDau(Integer chiSoNuocBanDau) {
        this.chiSoNuocBanDau = chiSoNuocBanDau;
    }
    public Integer getChiSoNuocCuoi() {
        return this.chiSoNuocCuoi;
    }
    
    public void setChiSoNuocCuoi(Integer chiSoNuocCuoi) {
        this.chiSoNuocCuoi = chiSoNuocCuoi;
    }
    public Double getTienNuoc() {
        return this.tienNuoc;
    }
    
    public void setTienNuoc(Double tienNuoc) {
        this.tienNuoc = tienNuoc;
    }




}


