package entity;
// Generated Apr 1, 2019 7:59:34 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * HoaDonDichVu generated by hbm2java
 */
public class HoaDonDichVu  implements java.io.Serializable {


     private Serializable hoaDonDichVuId;
     private CanHo canHo;
     private HoaDon hoaDon;
     private Double tienDichVuCoBan;
     private Double tienGuiXe;
     private Double tongTien;
     private Serializable thang;
     private Set<GuiXe> guiXes = new HashSet<GuiXe>(0);

    public HoaDonDichVu() {
    }

	
    public HoaDonDichVu(Serializable hoaDonDichVuId) {
        this.hoaDonDichVuId = hoaDonDichVuId;
    }
    public HoaDonDichVu(Serializable hoaDonDichVuId, CanHo canHo, HoaDon hoaDon, Double tienDichVuCoBan, Double tienGuiXe, Double tongTien, Serializable thang, Set<GuiXe> guiXes) {
       this.hoaDonDichVuId = hoaDonDichVuId;
       this.canHo = canHo;
       this.hoaDon = hoaDon;
       this.tienDichVuCoBan = tienDichVuCoBan;
       this.tienGuiXe = tienGuiXe;
       this.tongTien = tongTien;
       this.thang = thang;
       this.guiXes = guiXes;
    }
   
    public Serializable getHoaDonDichVuId() {
        return this.hoaDonDichVuId;
    }
    
    public void setHoaDonDichVuId(Serializable hoaDonDichVuId) {
        this.hoaDonDichVuId = hoaDonDichVuId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public HoaDon getHoaDon() {
        return this.hoaDon;
    }
    
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }
    public Double getTienDichVuCoBan() {
        return this.tienDichVuCoBan;
    }
    
    public void setTienDichVuCoBan(Double tienDichVuCoBan) {
        this.tienDichVuCoBan = tienDichVuCoBan;
    }
    public Double getTienGuiXe() {
        return this.tienGuiXe;
    }
    
    public void setTienGuiXe(Double tienGuiXe) {
        this.tienGuiXe = tienGuiXe;
    }
    public Double getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Double tongTien) {
        this.tongTien = tongTien;
    }
    public Serializable getThang() {
        return this.thang;
    }
    
    public void setThang(Serializable thang) {
        this.thang = thang;
    }
    public Set<GuiXe> getGuiXes() {
        return this.guiXes;
    }
    
    public void setGuiXes(Set<GuiXe> guiXes) {
        this.guiXes = guiXes;
    }




}


