package entity;
// Generated Apr 1, 2019 7:59:34 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ThongTinKhachHang generated by hbm2java
 */
public class ThongTinKhachHang  implements java.io.Serializable {


     private Serializable khachHangId;
     private CanHo canHo;
     private Serializable tenKhachHang;
     private String cmnd;
     private Boolean gioiTinh;
     private Serializable soDt;
     private Serializable email;
     private Boolean chuHo;

    public ThongTinKhachHang() {
    }

	
    public ThongTinKhachHang(Serializable khachHangId) {
        this.khachHangId = khachHangId;
    }
    public ThongTinKhachHang(Serializable khachHangId, CanHo canHo, Serializable tenKhachHang, String cmnd, Boolean gioiTinh, Serializable soDt, Serializable email, Boolean chuHo) {
       this.khachHangId = khachHangId;
       this.canHo = canHo;
       this.tenKhachHang = tenKhachHang;
       this.cmnd = cmnd;
       this.gioiTinh = gioiTinh;
       this.soDt = soDt;
       this.email = email;
       this.chuHo = chuHo;
    }
   
    public Serializable getKhachHangId() {
        return this.khachHangId;
    }
    
    public void setKhachHangId(Serializable khachHangId) {
        this.khachHangId = khachHangId;
    }
    public CanHo getCanHo() {
        return this.canHo;
    }
    
    public void setCanHo(CanHo canHo) {
        this.canHo = canHo;
    }
    public Serializable getTenKhachHang() {
        return this.tenKhachHang;
    }
    
    public void setTenKhachHang(Serializable tenKhachHang) {
        this.tenKhachHang = tenKhachHang;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public Boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Serializable getSoDt() {
        return this.soDt;
    }
    
    public void setSoDt(Serializable soDt) {
        this.soDt = soDt;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Boolean getChuHo() {
        return this.chuHo;
    }
    
    public void setChuHo(Boolean chuHo) {
        this.chuHo = chuHo;
    }




}


