package entity;
// Generated Apr 1, 2019 7:59:34 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String userId;
     private String pass;
     private String ten;
     private String email;
     private String soDt;
     private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

    public Users() {
    }

	
    public Users(String userId) {
        this.userId = userId;
    }
    public Users(String userId, String pass, String ten, String email, String soDt, Set<HoaDon> hoaDons) {
       this.userId = userId;
       this.pass = pass;
       this.ten = ten;
       this.email = email;
       this.soDt = soDt;
       this.hoaDons = hoaDons;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSoDt() {
        return this.soDt;
    }
    
    public void setSoDt(String soDt) {
        this.soDt = soDt;
    }
    public Set<HoaDon> getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }




}


